model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    ckpt_path: ./logs/2023-02-23T09-38-56_aiahmi_kl_64x64xX/checkpoints/epoch=000362.ckpt
    monitor: "val/rec_loss"
    embed_dim: 6
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        disc_in_channels: 6
        kl_weight: 0.000001
        disc_weight: 0.5
        perceptual_weight: 0.0

    ddconfig:
      double_z: True
      z_channels: 6
      resolution: 256
      in_channels: 6
      out_ch: 6
      ch: 128
      ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8 
    num_workers: 1
    wrap: True
    train:
      target: ldm.data.aiahmi.AIAHMITrain
      params:
        size: 256
    validation:
      target: ldm.data.aiahmi.AIAHMIValidation
      params:
        size: 256

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 16
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
