model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: class
    image_size: 64
    channels: 6
    concat_mode: true
    conditioning_key: concat
    cond_stage_trainable: true
    monitor: val/loss
    use_ema: false 

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 15
        out_channels: 6
        model_channels: 128
        attention_resolutions:
        - 32
        - 16
        - 8
        num_res_blocks: 2
        channel_mult:
        - 1
        - 4
        - 8
        num_heads: 8

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 6
        ckpt_path: logs/2023-02-27T13-27-01_aiahmi_kl_64x64xX/checkpoints/epoch=000104.ckpt

        ddconfig:
          double_z: True 
          z_channels: 6
          resolution: 256
          in_channels: 6
          out_ch: 6
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.SpatialRescaler
      params:
        n_stages: 2
        in_channels: 9
        out_channels: 9
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 72 
    wrap: false
    num_workers: 2
    train:
      target: ldm.data.aiahmi.AIAHMITrain
      params:
        size: 256
          #crop_size: 512
          #segmentation_to_float32: true
    validation:
      target: ldm.data.aiahmi.AIAHMIValidation
      params:
        size: 256
          #crop_size: 512
          #segmentation_to_float32: true

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 16
        increase_log_steps: False
